// general
export const TOGGLE_PRELOADING = 'TOGGLE_PRELOADING';
export const TOGGLE_IS_MODAL = 'TOGGLE_IS_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_ADD_TASK = 'TOGGLE_ADD_TASK';
export const TOGGLE_CREATE_STAFF = 'TOGGLE_CREATE_STAFF';
export const TOGGLE_SET_LEAVE = 'TOGGLE_SET_LEAVE';
export const TOGGLE_SHOW_HISTORY = 'TOGGLE_SHOW_HISTORY';
export const TOGGLE_CREATE_INVENTORY = 'TOGGLE_CREATE_INVENTORY';
export const TOGGLE_EDIT_INVENTORY = 'TOGGLE_EDIT_INVENTORY';
export const TOGGLE_APPROVE_TRANSACTION = 'TOGGLE_APPROVE_TRANSACTION';
export const TOGGLE_UPDATE_QTY = 'TOGGLE_UPDATE_QTY';
export const TOGGLE_CREATE_INV_CAT = 'TOGGLE_CREATE_INV_CAT';
export const TOGGLE_EDIT_INV_CAT = 'TOGGLE_EDIT_INV_CAT';
export const TOGGLE_CREATE_ROLE = 'TOGGLE_CREATE_ROLE';
export const TOGGLE_EDIT_STAFF = 'TOGGLE_EDIT_STAFF';
export const TOGGLE_VIEW_APPRAISAL = 'TOGGLE_VIEW_APPRAISAL';
export const TOGGLE_VIEW_PAYROLL_HISTORY = 'TOGGLE_VIEW_PAYROLL_HISTORY';
export const TOGGLE_VIEW_CURRENT_PAYROLL = 'TOGGLE_VIEW_CURRENT_PAYROLL';
export const TOGGLE_PREPARE_PAYROLL = 'TOGGLE_PREPARE_PAYROLL';
export const TOGGLE_EDIT_PAYROLL = 'TOGGLE_EDIT_PAYROLL';
export const TOGGLE_REGISTER_NEW_PATIENT = 'OGGLE_REGISTER_NEW_PATIENT';
export const TOGGLE_CREATE_APPOINTMENT = 'TOGGLE_CREATE_APPOINTMENT';
export const TOGGLE_VIEW_APPOINTMENT_DETAIL = 'TOGGLE_VIEW_APPOINTMENT_DETAIL';
export const SET_PATIENT_RECORD = 'SET_PATIENT_RECORD';
export const TOGGLE_VIEW_PAYPOINT = 'TOGGLE_VIEW_PAYPOINT';
export const TOGGLE_CREATE_VOUCHER = 'TOGGLE_CREATE_VOUCHER';
export const TOGGLE_APPLY_VOUCHER = 'TOGGLE_APPLY_VOUCHER';
export const TOGGLE_CREATE_LABOUR_MEASUREMENT =
	'TOGGLE_CREATE_LABOUR_MEASUREMENT';
export const TOGGLE_CREATE_RISK_ASSESSMENT = 'TOGGLE_CREATE_RISK_ASSESSMENT';
export const TOGGLE_CREATE_RECORD_DELIVERY = 'TOGGLE_CREATE_RECORD_DELIVERY';
export const TOGGLE_CREATE_RECORD_VITAL = 'TOGGLE_CREATE_RECORD_VITAL';
export const TOGGLE_UPLOAD_SERVICE = 'TOGGLE_UPLOAD_SERVICE';
export const TOGGLE_UPLOAD_DIAGNOSIS = 'TOGGLE_UPLOAD_DIAGNOSIS';
export const TOGGLE_UPLOAD_HMO = 'TOGGLE_UPLOAD_HMO';
export const TOGGLE_UPLOAD_HMO_TARIFF = 'TOGGLE_UPLOAD_HMO_TARIFF';
export const TOGGLE_EDIT_SERIVCE = 'TOGGLE_EDIT_SERIVCE';
export const TOGGLE_CREATE_CLINICAL_TASK = 'TOGGLE_CREATE_CLINICAL_TASK';
export const TOGGLE_OPEN_ENCOUNTER = 'TOGGLE_OPEN_ENCOUNTER';
export const TOGGLE_ADD_CAFETERIA_FILE = 'TOGGLE_ADD_CAFETERIA_FILE';
// user
export const SET_PROFILE = 'SET_PROFILE';
export const SIGN_OUT = 'SIGN_OUT';
export const TOGGLE_MODE = 'TOGGLE_MODE';
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const INIT_MODE = 'INIT_MODE';
export const INIT_FULLSCREEN = 'INIT_FULLSCREEN';
export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';

// inventory
export const LOAD_INV_CATEGORIES = 'LOAD_INV_CATEGORIES';
export const LOAD_INVENTORY = 'LOAD_INVENTORY';
export const ADD_INV_CATEGORY = 'ADD_INV_CATEGORY';
export const UPDATE_INV_CATEGORY = 'UPDATE_INV_CATEGORY';
export const LOAD_INVENTORIES = 'LOAD_INVENTORIES';
export const ADD_INVENTORY = 'ADD_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const LOAD_SUB_CATEGORIES = 'LOAD_SUB_CATEGORIES';
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';

// role
export const LOAD_ROLES = 'LOAD_ROLES';
export const NEW_ROLE = 'NEW_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';

// hr
export const LOAD_STAFFS = 'LOAD_STAFFS';
export const LOAD_DUTY_ROSTERS = 'LOAD_DUTY_ROSTERS';
export const LOAD_LEAVE = 'LOAD_LEAVE';
export const LOAD_APPRAISALS = 'LOAD_APPRAISALS';
export const LOAD_PAYROLL = 'LOAD_PAYROLL';
export const ADD_STAFF = 'ADD_STAFF';
export const LOAD_UNPAID_PAYROLL = 'LOAD_UNPAID_PAYROLL';
export const LOAD_PAYROLL_HISTORY = 'LOAD_PAYROLL_HISTORY';

//Department
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

//Rooms
export const ADD_ROOM = 'ADD_ROOM';
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const ADD_ROOM_CATEGORY = 'ADD_ROOM_CATEGORY';
export const GET_ALL_ROOM_CATEGORIES = 'GET_ALL_ROOM_CATEGORIES';
export const UPDATE_ROOM_CATEGORY = 'UPDATE_ROOM_CATEGORY';
export const DELETE_ROOM_CATEGORY = 'DELETE_ROOM_CATEGORY';

//Lab
export const ADD_LAB_TEST = 'ADD_LAB_TEST';
export const GET_ALL_LAB_TESTS = 'GET_LAB_TESTS';
export const UPDATE_LAB_TEST = 'UPDATE_LAB_TEST';
export const DELETE_LAB_TEST = 'DELETE_LAB_TEST';
export const ADD_LAB_TEST_CATEGORY = 'ADD_LAB_TEST_CATEGORY';
export const GET_ALL_LAB_TEST_CATEGORIES = 'GET_ALL_LAB_TEST_CATEGORIES';
export const UPDATE_LAB_TEST_CATEGORY = 'UPDATE_LAB_TEST_CATEGORY';
export const DELETE_LAB_TEST_CATEGORY = 'DELETE_LAB_TEST_CATEGORY';
export const ADD_LAB_TEST_PARAMETER = 'ADD_LAB_TEST_PARAMETER';
export const GET_ALL_LAB_TEST_PARAMETERS = 'GET_ALL_LAB_TEST_PARAMETERS';
export const UPDATE_LAB_TEST_PARAMETER = 'UPDATE_LAB_TEST_PARAMETER';
export const DELETE_LAB_TEST_PARAMETER = 'DELETE_LAB_TEST_PARAMETER';
export const ADD_LAB_GROUP = 'ADD_LAB_GROUP';
export const UPDATE_LAB_GROUP = 'UPDATE_LAB_GROUP';
export const DELETE_LAB_GROUP = 'DELETE_LAB_GROUP';
export const GET_ALL_LAB_GROUPS = 'GET_ALL_LAB_GROUPS';

//Hmo
export const ADD_HMO = 'ADD_HMO';
export const FETCH_ALL_HMOS_DATA = 'FETCH_ALL_HMOS_DATA';
export const UPDATE_HMO = 'GET_ALL_HMOS';
export const DELETE_HMO = 'DELTE_HMO';
export const FETCH_HMO_TARIFF = 'FETCH_HMO_TARIFF';

//Leave category
export const ADD_LEAVE_CATEGORY = 'ADD_LEAVE_CATEGORY';
export const GET_ALL_LEAVE_CATEGORIES = 'GET_ALL_LEAVE_CATEGORIES';
export const UPDATE_LEAVE_CATEGORY = 'UPDATE_LEAVE_CATEGORY';
export const DELETE_LEAVE_CATEGORY = 'DELETE_LEAVE_CATEGORY';
export const UPLOAD_HMO = 'UPLOAD_HMO';
//Specialization
export const ADD_SPECIALIZATION = 'ADD_SPECIALIZATION';
export const GET_ALL_SPECIALIZATIONS = 'GET_ALL_SPECIALIZATION';
export const UPDATE_SPECIALIZATION = 'UPDATE_SPECIALIZATION';
export const DELETE_SPECIALIZATION = 'DELETE_SPECIALIZATION';

//Consultation
export const ADD_CONSULTATING_ROOM = 'ADD_CONSULTATING_ROOM';
export const GET_ALL_CONSULTATING_ROOMS = 'GET_ALL_CONSULTATING_ROOMS';
export const UPDATE_CONSULTATING_ROOM = 'UPDATE_CONSULTATING_ROOM';
export const DELETE_CONSULTATING_ROOM = 'DELETE_CONSULTATING_ROOM';

// utility
export const LOAD_BANKS = 'LOAD_BANKS';
export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';

// patient
export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';
export const SAVE_PATIENT_DETAILS = 'SAVE_PATIENT_DETAILS';
export const CREATE_LAB_REQUEST = 'CREATE_LAB_REQUEST';
export const GET_REQUESTS_BY_TYPE = 'GET_REQUESTS_BY_TYPE';

//cafeteria
export const LOAD_PATIENTS = 'LOAD_PATIENTS ';

//Permission
export const ADD_PERMISSION = 'ADD_PERMISSION';
export const GET_ALL_PERMISSIONS = 'GET_ALL_PERMISSIONS';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION';

//Service Category
export const ADD_SERVICE_CATEGORY = 'ADD_SERVICE_CATEGORY';
export const GET_ALL_SERVICE_CATEGORIES = 'GET_ALL_SERVICE_CATEGORIES';
export const UPDATE_SERVICE_CATEGORY = 'UPDATE_SERVICE_CATEGORY';
export const DELETE_SERVICE_CATEGORY = 'DELETE_SERVICE_CATEGORY';

//Services
export const UPLOAD_SERVICE = 'UPLOAD_SERVICE';
export const GET_ALL_SERIVCES = 'GET_ALL_SERIVCES';
export const DOWNLOAD_SERVICE = 'DOWNLOAD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

//Upload diagnosis
export const UPLOAD_DIAGNOSIS = 'UPLOAD_DIAGNOSIS';
export const GET_ALL_DIAGNOSISES = 'GET_ALL_DIAGNOSISES';
export const UPDATE_DIAGNOSIS = 'UPDATE_DIAGNOSIS';
export const DELETE_DIAGNOSIS = 'DELETE_DIAGNOSIS';

//Patient
export const SAVE_ALLERGIES = 'SAVE_ALLERGIES';
export const GET_ALLERGIES = 'GET_ALLERGIES';
export const ALLERGY = 'ALLERGY';
export const UPDATE_ALLERGY = 'UPDATE_ALLERGY';
export const DELETE_ALLERGY = 'DELETE_ALLERGY';
export const LOAD_ENCOUNTERS = 'LOAD_ENCOUNTERS';
export const LOAD_PATIENT_UPLOAD_DATA = 'LOAD_PATIENT_UPLOAD_DATA';
export const ADD_PATIENT_UPLOAD_DATA = 'ADD_PATIENT_UPLOAD_DATA';
export const LOAD_PATIENT_PROCEDURE_DATA = 'LOAD_PATIENT_PROCEDURE_DATA';
export const ADD_PATIENT_PROCEDURE_DATA = 'ADD_PATIENT_PROCEDURE_DATA';

//Physiotherapies
export const GET_PHYSIOTHERAPIES = 'GET_PHYSIOTHERAPIES';

//Request service
export const ADD_REQUEST_SERVICE = 'ADD_REQUEST_SERVICE';
export const GET_ALL_REQUEST_SERVICES = 'GET_ALL_REQUEST_SERVICES';
export const UPDATE_REQUEST_SERVICE = 'UPDATE_REQUEST_SERVICE';
export const DELETE_REQUEST_SERVICE = 'DELETE_REQUEST_SERVICE';

export const GET_DENTISTRY_REQUESTS = 'GET_DENTISTRY_REQUESTS';
export const GET_IMAGING_REQUESTS = 'GET_IMAGING_REQUESTS';
export const GET_OPTHALMOLOGY_REQUESTS = 'GET_OPTHALMOLOGY_REQUESTS';

//Vitals
export const UPDATE_VITALS = 'UPDATE_VITALS';
export const LOAD_VITALS = 'LOAD_VITALS';

//Transaction
export const CREATE_VOUCHER = 'CREATE_VOUCHER';
export const LOAD_VOUCHER = 'LOAD_VOUCHER';
export const UPDATE_VOUCHER = 'UPDATE_VOUCHER';
export const DELETE_VOUCHER = 'DELETE_VOUCHER';
export const LOAD_TODAY_TRANSACTION = 'LOAD_TODAY_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const LOAD_RECENT_TRANSACTION = 'LOAD_RECENT_TRANSACTION';

//cafeteria
export const ADD_CAFETERIA_CATEGORY = 'ADD_CAFETERIA_CATEGORY';
export const GET_ALL_CAFETERIA_CATEGORY = 'GET_ALL_CAFETERIA_CATEGORY';
export const UPDATE_CAFETERIA_CATEGORY = 'UPDATE_CAFETERIA_CATEGORY';
export const DELETE_CAFETERIA_CATEGORY = 'DELETE_CAFETERIA_CATEGORY';

export const ADD_CAFETERIA_ITEM = 'ADD_CAFETERIA_ITEM ';
export const GET_ALL_CAFETERIA_ITEMS = 'GET_ALL_CAFETERIA_ITEMS';
export const UPDATE_CAFETERIA_ITEM = 'UPDATE_CAFETERIA_ITEM';
export const DELETE_CAFETERIA_ITEM = 'DELETE_CAFETERIA_ITEM';
export const FILTER_CAFETERIA_ITEM = 'FILTER_CAFETERIA_ITEM';

export const ADD_CAFETERIA_INV_CATEGORY = 'ADD_CAFETERIA_INV_CATEGORY';
export const GET_ALL_CAFETERIA_INV_CATEGORY = 'GET_ALL_CAFETERIA_INV_CATEGORY';
export const UPDATE_CAFETERIA_INV_CATEGORY = 'UPDATE_CAFETERIA_INV_CATEGORY';
export const DELETE_CAFETERIA_INV_CATEGORY = 'DELETE_CAFETERIA_INV_CATEGORY';

export const ADD_CAFETERIA_INVENTORY = 'ADD_CAFETERIA_INVENTORY';
export const GET_ALL_CAFETERIA_INVENTORY = 'GET_ALL_CAFETERIA_INVENTORY';
export const UPDATE_CAFETERIA_INVENTORY = 'UPDATE_CAFETERIA_INVENTOR';
export const DELETE_CAFETERIA_INVENTORY = 'DELETE_CAFETERIA_INVENTORY';
