// general
export const TOGGLE_PRELOADING = 'TOGGLE_PRELOADING';
export const TOGGLE_IS_MODAL = 'TOGGLE_IS_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_ADD_TASK = "TOGGLE_ADD_TASK";
export const TOGGLE_CREATE_STAFF = 'TOGGLE_CREATE_STAFF';
export const TOGGLE_SET_LEAVE = 'TOGGLE_SET_LEAVE';
export const TOGGLE_SHOW_HISTORY = 'TOGGLE_SHOW_HISTORY';
export const TOGGLE_CREATE_INVENTORY = 'TOGGLE_CREATE_INVENTORY';
export const TOGGLE_EDIT_INVENTORY = 'TOGGLE_EDIT_INVENTORY';
export const TOGGLE_UPDATE_QTY = 'TOGGLE_UPDATE_QTY';
export const TOGGLE_EDIT_STAFF = 'TOGGLE_EDIT_STAFF';
export const TOGGLE_VIEW_APPRAISAL = 'TOGGLE_VIEW_APPRAISAL';
export const TOGGLE_VIEW_PAYROLL_HISTORY = 'TOGGLE_VIEW_PAYROLL_HISTORY';
export const TOGGLE_VIEW_CURRENT_PAYROLL = 'TOGGLE_VIEW_CURRENT_PAYROLL';
export const TOGGLE_PREPARE_PAYROLL = 'TOGGLE_PREPARE_PAYROLL';
export const TOGGLE_EDIT_PAYROLL = 'TOGGLE_EDIT_PAYROLL';
export const TOGGLE_REGISTER_NEW_PATIENT = "TOGGLE_REGISTER_NEW_PATIENT";
export const TOGGLE_CREATE_APPOINTMENT = "TOGGLE_CREATE_APPOINTMENT";
export const TOGGLE_VIEW_APPOINTMENT_DETAIL = "TOGGLE_VIEW_APPOINTMENT_DETAIL";
export const SET_PATIENT_RECORD = 'SET_PATIENT_RECORD';

// user
export const SET_PROFILE = "SET_PROFILE";
export const SIGN_OUT = "SIGN_OUT";
export const TOGGLE_MODE = 'TOGGLE_MODE';
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const INIT_MODE = 'INIT_MODE';
export const INIT_FULLSCREEN = 'INIT_FULLSCREEN';
export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';

// inventory
export const LOAD_INV_CATEGORIES = 'LOAD_INV_CATEGORIES';
export const LOAD_INVENTORY = 'LOAD_INVENTORY';
export const ADD_INV_CATEGORY = 'ADD_INV_CATEGORY';
export const UPDATE_INV_CATEGORY = 'UPDATE_INV_CATEGORY';
export const LOAD_INVENTORIES = 'LOAD_INVENTORIES';
export const ADD_INVENTORY = 'ADD_INVENTORY';
export const LOAD_SUB_CATEGORIES = 'LOAD_SUB_CATEGORIES';
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';

// role
export const LOAD_ROLES = 'LOAD_ROLES';
export const NEW_ROLE = 'NEW_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';

// hr
export const LOAD_STAFFS = 'LOAD_STAFFS';
export const LOAD_DUTY_ROSTERS = 'LOAD_DUTY_ROSTERS';
export const LOAD_LEAVE = 'LOAD_LEAVE';
export const LOAD_APPRAISALS = 'LOAD_APPRAISALS';
export const LOAD_PAYROLL = 'LOAD_PAYROLL';
export const ADD_STAFF = 'ADD_STAFF';

//Department
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

//Rooms
export const ADD_ROOM = "ADD_ROOM";
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const ADD_ROOM_CATEGORY = "ADD_ROOM_CATEGORY";
export const GET_ALL_ROOM_CATEGORIES = "GET_ALL_ROOM_CATEGORIES";
export const UPDATE_ROOM_CATEGORY = "UPDATE_ROOM_CATEGORY";
export const DELETE_ROOM_CATEGORY = "DELETE_ROOM_CATEGORY";

//Lab
export const ADD_LAB_TEST = "ADD_LAB_TEST";
export const GET_ALL_LAB_TESTS = "GET_LAB_TESTS";
export const UPDATE_LAB_TEST = "UPDATE_LAB_TEST";
export const DELETE_LAB_TEST = "DELETE_LAB_TEST";
export const ADD_LAB_TEST_CATEGORY = "ADD_LAB_TEST_CATEGORY";
export const GET_ALL_LAB_TEST_CATEGORIES = "GET_ALL_LAB_TEST_CATEGORIES";
export const UPDATE_LAB_TEST_CATEGORY = "UPDATE_LAB_TEST_CATEGORY";
export const DELETE_LAB_TEST_CATEGORY = "DELETE_LAB_TEST_CATEGORY";
export const ADD_LAB_TEST_PARAMETER = "ADD_LAB_TEST_PARAMETER";
export const GET_ALL_LAB_TEST_PARAMETERS = "GET_ALL_LAB_TEST_PARAMETERS";
export const UPDATE_LAB_TEST_PARAMETER = "UPDATE_LAB_TEST_PARAMETER";
export const DELETE_LAB_TEST_PARAMETER = "DELETE_LAB_TEST_PARAMETER";

//Hmo
export const ADD_HMO = "ADD_HMO"
export const GET_ALL_HMOS = "GET_ALL_HMOS"
export const UPDATE_HMO = "GET_ALL_HMOS"
export const DELETE_HMO = "DELTE_HMO"

//Leave category
export const ADD_LEAVE_CATEGORY = "ADD_LEAVE_CATEGORY";
export const GET_ALL_LEAVE_CATEGORIES = "GET_ALL_LEAVE_CATEGORIES";
export const UPDATE_LEAVE_CATEGORY = "UPDATE_LEAVE_CATEGORY";
export const DELETE_LEAVE_CATEGORY = "DELETE_LEAVE_CATEGORY";

// utility
export const LOAD_BANKS = 'LOAD_BANKS';
export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';
